### ISSUE TITLE
Can this be used to speed up video decoding on the switch?

### ISSUE THREAD

**Issue by fknfilewalker** [devkitPro/deko3d#12]
There is an ongoing motivation to port moonlight for the switch e.g. [XITRIX/Moonlight-Switch](https://github.com/XITRIX/Moonlight-Switch). It already works quite good but one thing that is still missing is gpu accelerated video decoding, mainly through NVDEC, which currently is not reverse engineered for switch homebrew. Could deko3d be of any help in this regard?

**Comment by masagrator** [comment]
No. deko3d is not related to hardware video decoding.
nvdec has its own dedicated services that needs to be used for video decoding and deko3d is not touching them.
