### ISSUE TITLE
jetson nano

### ISSUE THREAD

**Issue by uglyoldbob** [devkitPro/deko3d#22]
Is there any possibility of using this driver on the jetson nano, which uses a modified version of the gpu on the nintendo switch which this supports?

**Comment by fincs** [comment]
Unfortunately the answer would be no. deko3d relies on libnx and Horizon OS to work, whereas the Jetson Nano runs a Nvidia-specific distribution of Linux. In any case, on a Jetson Nano you should have access to the official Nvidia userland libraries, which include OpenGL and Vulkan implementations.
