### ISSUE TITLE
Error codes for the C API

### ISSUE THREAD

**Issue by AmelieHeinrich** [devkitPro/deko3d#23]
#### Overview:
It would be nice if instead of returning a handle, the Deko3D init functions would take a pointer to the resulting handle and return an error code instead.</br>

#### Nature of Request:  
- Change

### Why would this feature be useful?
Currently the C API does not have any way of getting specific errors (currently struggling with a dkSwapchainCreate error that doesn't show me the error, because Deko3D just crashes when the C API reaches an error).</br>
It would make the C API way nicer to use and debug.</br>

### Example
Instead of:
```c
DkSwapchain dkSwapchainCreate(DkSwapchainMaker const* maker);
```
Do this:
```
DkResult dkSwapchainCreate(DkSwapchainMaker const* maker, DkSwapchain* out);
```

**Comment by fincs** [comment]
Regardless of the API used (C or C++), errors in deko3d are considered fatal, as in requiring program execution to be terminated. If you need to troubleshoot a deko3d error, you might want to link to `-ldeko3dd`, the debugging version of the library. This version will display an error box on screen with more information about what failed exactly.

**Comment by AmelieHeinrich** [comment]
I understand now, sadly the error codes given by the Deko3D C API do not help at all.
For instance, here in dk_swapchain.cpp:158
```cpp
if (res != DkResult_Success)
{
	delete obj;
	DK_ERROR(res, "initialization failure");
}
```
How can I guess the error? It would be nice if Deko3D gave the error code in the message as well.

**Comment by AmelieHeinrich** [comment]
(Deleted earlier comment, the emulators just decided to sneak the error code in the window title. Great xD)

**Comment by fincs** [comment]
> How can I guess the error? It would be nice if Deko3D gave the error code in the message as well.

The debugging version of the library does include both the error code and the message in the crash screen. However in this case, it might be a bit ambiguous since there are multiple failure points stemming from several NWindow functions, but this isn't generally the case.

> The only way to actually get the error code would be to use the C++ API

This isn't true. The C++ API is a wrapper around the public C API. The code you see in dk_swapchain.cpp is internal to the library and not exposed outside.

**Comment by AmelieHeinrich** [comment]
You're right, I didn't check the error message thoroughly. However, I think it would be great if the error codes could indeed be a bit more expensive. To know if (for instance, in swapchain creation), whether it's nwindowSetDimensions or nwindowConfigureBuffer that fails.
