### ISSUE TITLE
[Request] Multiple layer copies for dkCmdBufCopyBufferToImage

### ISSUE THREAD

**Issue by jackoalan** [devkitPro/deko3d#4]
Would it be possible to grant dkCmdBufCopyBufferToImage the ability to copy multiple image layers? vkCmdCopyBufferToImage can do it with imageSubresource.layerCount > 1. The process is similar to copying 2D slices of a 3D image which it already looks like dkCmdBufCopyBufferToImage can do.

Edit: Actually it looks like the z and depth parameters of DkImageRect can double up for selecting a layer range (in a 2D image anyway, not sure about the 1D case). Is my observation accurate here?

**Comment by fincs** [comment]
I don't understand your request. Both dkCmdBufCopyBufferToImage and dkCmdBufBlitImage are already supporting layered copies (multilayer even), this is even made use of in the deko_console examples. All of the other copy functions (barring ResolveImage which is special purpose) are not implemented anyway.

**Comment by jackoalan** [comment]
Cool! Thanks for pointing out the deko_console examples. I'm working on porting an existing graphics engine from Vulkan (which treats layer ranges separately from 3D extents). Just needed that detail clarified.
